name: Syncmoney
version: '${version}'
main: noietime.syncmoney.Syncmoney
description: Cross-server economy synchronization plugin for Minecraft
api-version: '1.20'
folia-supported: true

dependencies:
  server:
    Vault:
      load: AFTER
      required: true
    CMI:
      load: AFTER
      required: false
    PlaceholderAPI:
      load: AFTER
      required: false

